services:
  nextjs-app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./logs:/app/logs
    environment:
      - NODE_ENV=production
      - BASE_SEPOLIA_RPC=${BASE_SEPOLIA_RPC}
      - ERC20_CONTRACT_ADDRESS=${ERC20_CONTRACT_ADDRESS}
      - ENCRYPTED_ERC20_CONTRACT_ADDRESS=${ENCRYPTED_ERC20_CONTRACT_ADDRESS}
      - INCO_ENV=${INCO_ENV}
      - REOWN_APP_ID=${REOWN_APP_ID}
      # Logging configuration
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - SERVICE_NAME=${SERVICE_NAME:-comfy-consumer}
      - APP_VERSION=${APP_VERSION:-1.0.0}
