// abis/*.json → src/generated/*.ts, `as const`.
//   pnpm --filter @comfy/config gen:abis
import { readFileSync, writeFileSync, readdirSync, mkdirSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const src = join(root, "abis");
const out = join(root, "src", "generated");
mkdirSync(out, { recursive: true });

const camel = (s) => {
  const lead = s.match(/^([A-Z]+)(?![a-z])/);
  return lead
    ? lead[1].toLowerCase() + s.slice(lead[1].length)
    : s.charAt(0).toLowerCase() + s.slice(1);
};
const files = readdirSync(src).filter((f) => f.endsWith(".json"));
const index = [];

for (const file of files) {
  const name = file.replace(/\.json$/, "");
  const parsed = JSON.parse(readFileSync(join(src, file), "utf8"));
  const abi = Array.isArray(parsed) ? parsed : parsed.abi;
  if (!Array.isArray(abi)) throw new Error(`${file}: no ABI array found`);

  const varName = `${camel(name)}Abi`;
  const body = [
    `// Generated from abis/${file} by scripts/gen-abis.mjs. Do not edit.`,
    `export const ${varName} = ${JSON.stringify(abi, null, 2)} as const;`,
    "",
  ].join("\n");
  writeFileSync(join(out, `${camel(name)}.ts`), body);
  index.push(`export { ${varName} } from "./${camel(name)}.js";`);
  console.log(`  ${file} → src/generated/${camel(name)}.ts (${abi.length} items)`);
}

writeFileSync(
  join(out, "index.ts"),
  ["// Generated by scripts/gen-abis.mjs. Do not edit.", ...index.sort(), ""].join("\n"),
);
console.log(`wrote ${files.length} ABIs`);
