name: Build Next.js Docker Image

on:
  push:
    branches:
      - main

env:
  REGISTRY: gcr.io
  PROJECT_ID: inco-core
  IMAGE_NAME: comfy-consumer

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # for creating tags
      id-token: write  # for GCP OIDC auth
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      # Generate version
      - name: Generate version
        id: version
        run: |
          # Get latest tag
          latest_tag=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          
          # Increment patch version
          IFS='.' read -r -a version_parts <<< "${latest_tag#v}"
          new_patch=$((${version_parts[2]} + 1))
          new_version="${version_parts[0]}.${version_parts[1]}.$new_patch"
          
          echo "New version: v$new_version"
          echo "new_version=$new_version" >> $GITHUB_OUTPUT
          
          # Create and push new tag
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git tag -a "v$new_version" -m "Release v$new_version"
          git push origin "v$new_version"

      # Authenticate to GCP - FIXED PROJECT NUMBER
      - uses: 'google-github-actions/auth@v2'
        with:
          project_id: ${{ env.PROJECT_ID }}
          workload_identity_provider: 'projects/79476508147/locations/global/workloadIdentityPools/github-pool-core/providers/github-provider'

      # Set up gcloud CLI
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Configure Docker for GCR
      - name: Configure Docker
        run: |
          gcloud auth configure-docker gcr.io

      # Build and push using Docker
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }}:v${{ steps.version.outputs.new_version }}